import time


lista_estudiantes = [
    ("Juanki", 85),
    ("Ana", 92),
    ("Pedro", 85),
    ("Maria", 92),
    ("Luis", 78),
    ("Diego", 99),
    ("Pacheco",65),
    ("Pacheco",65),
    ("Juanki", 81),
    ("Ana", 93),
    ("Pedro", 84),
    ("Maria", 98),
    ("Luis", 77),
    ("Diego", 94),
    ("Pacheco",66),
    ("Pacheco",62),
     ("Juanki", 85),
    ("Ana", 92),
    ("Pedro", 85),
    ("Maria", 92),
    ("Luis", 78),
    ("Diego", 99),
    ("Pacheco",65),
    ("Pacheco",65),
     ("Juanki", 85),
    ("Ana", 92),
    ("Pedro", 85),
    ("Maria", 92),
    ("Luis", 78),
    ("Diego", 99),
    ("Pacheco",65),
    ("Pacheco",65),
     ("Juanki", 85),
    ("Ana", 92),
    ("Pedro", 85),
    ("Maria", 92),
    ("Luis", 78),
    ("Diego", 99),
    ("Pacheco",65),
    ("Pacheco",65),
    ("Juanki", 85),
    ("Ana", 92),
    ("Pedro", 85),
    ("Maria", 92),
    ("Luis", 78),
    ("Diego", 99),
    ("Pacheco",65),
    ("Pacheco",65),
    ("Juanki", 81),
    ("Ana", 93),
    ("Pedro", 84),
    ("Maria", 98),
    ("Luis", 77),
    ("Diego", 94),
    ("Pacheco",66),
    ("Pacheco",62),
     ("Juanki", 85),
    ("Ana", 92),
    ("Pedro", 85),
    ("Maria", 92),
    ("Luis", 78),
    ("Diego", 99),
    ("Pacheco",65),
    ("Pacheco",65),
     ("Juanki", 85),
    ("Ana", 92),
    ("Pedro", 85),
    ("Maria", 92),
    ("Luis", 78),
    ("Diego", 99),
    ("Pacheco",65),
    ("Pacheco",65),
     ("Juanki", 85),
    ("Ana", 92),
    ("Pedro", 85),
    ("Maria", 92),
    ("Luis", 78),
    ("Diego", 99),
    ("Pacheco",65),
    ("Pacheco",65),
    ("Juanki", 85),
    ("Ana", 92),
    ("Pedro", 85),
    ("Maria", 92),
    ("Luis", 78),
    ("Diego", 99),
    ("Pacheco",65),
    ("Pacheco",65),
    ("Juanki", 81),
    ("Ana", 93),
    ("Pedro", 84),
    ("Maria", 98),
    ("Luis", 77),
    ("Diego", 94),
    ("Pacheco",66),
    ("Pacheco",62),
     ("Juanki", 85),
    ("Ana", 92),
    ("Pedro", 85),
    ("Maria", 92),
    ("Luis", 78),
    ("Diego", 99),
    ("Pacheco",65),
    ("Pacheco",65),
     ("Juanki", 85),
    ("Ana", 92),
    ("Pedro", 85),
    ("Maria", 92),
    ("Luis", 78),
    ("Diego", 99),
    ("Pacheco",65),
    ("Pacheco",65),
     ("Juanki", 85),
    ("Ana", 92),
    ("Pedro", 85),
    ("Maria", 92),
    ("Luis", 78),
    ("Diego", 99),
    ("Pacheco",65),
    ("Pacheco",65),
    ("Juanki", 85),
    ("Ana", 92),
    ("Pedro", 85),
    ("Maria", 92),
    ("Luis", 78),
    ("Diego", 99),
    ("Pacheco",65),
    ("Pacheco",65),
    ("Juanki", 81),
    ("Ana", 93),
    ("Pedro", 84),
    ("Maria", 98),
    ("Luis", 77),
    ("Diego", 94),
    ("Pacheco",66),
    ("Pacheco",62),
     ("Juanki", 85),
    ("Ana", 92),
    ("Pedro", 85),
    ("Maria", 92),
    ("Luis", 78),
    ("Diego", 99),
    ("Pacheco",65),
    ("Pacheco",65),
     ("Juanki", 85),
    ("Ana", 92),
    ("Pedro", 85),
    ("Maria", 92),
    ("Luis", 78),
    ("Diego", 99),
    ("Pacheco",65),
    ("Pacheco",65),
     ("Juanki", 85),
    ("Ana", 92),
    ("Pedro", 85),
    ("Maria", 92),
    ("Luis", 78),
    ("Diego", 99),
    ("Pacheco",65),
    ("Pacheco",65),

]

def bubble_sort(lista):
    n = len(lista)
    for i in range(n):
        for j in range(0, n - i - 1):
            #recoremos la lista estudiantes y accedemos al al nota con [1]
            #comparamos la nota de las listas
            if lista[j][1] < lista[j + 1][1]:
                #usamos una variable auxiliar que nos permita guadar temporalmente un valor
                #que será usado para modificar la posicion de la lista[j]
                aux=lista[j + 1]
                lista[j + 1]= lista[j]
                lista[j]=aux
             # comparamos por nombre usandon el operador >
            elif lista[j][1] == lista[j + 1][1] and lista[j][0] > lista[j + 1][0]:
                aux=lista[j + 1]
                lista[j + 1]= lista[j]
                lista[j]=aux

tiempo_inicio = time.time()
bubble_sort(lista_estudiantes)
tiempo_final = time.time()

tiempo_total= tiempo_final-tiempo_inicio

print("Lista de estudiantes ordenada :")
for estudiante in lista_estudiantes:
    print(estudiante)

print(f"Tiempo de ejecución: {tiempo_total:.12f} segundos")